@Restaurants.API_HostAddress = https://localhost:7210
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1
Content-Type: application/json

{
   "Name": "Sample patch",
   "Description": "This is a sample restaurant Description",
   "HasDelivery": true
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
    "Name": "Spaghetti Bolognase",
    "Description": "Tasty classic Italian Pasta",
    "Price": 50,
    "KiloCalories": 20


}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes
Content-Type: application/json

{
    "Name": "Testowy Tost",
    "Description": "Smakuwa Tost",
    "Price": 12.50,
    "KiloCarloies": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###
