@Restaurants.API_HostAddress = https://localhost:7210
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1
Content-Type: application/json

{
   "Name": "Sample patch",
   "Description": "This is a sample restaurant Description",
   "HasDelivery": true
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/2

###
