@Restaurants.API_HostAddress = https://localhost:7210
@token = CfDJ8NaqmwLYiH9MvKuHzIu8oKMI8EBhAevDKsGQag9WXkmbNBA1wnYYohywD-eXh3aKbtkHBqJFWPkPVBOfWBjW3GcZiTXKtFQsolYjo8bmU_nAALaYxEm1_kLrTiSYyzLeCEZZ1eKMR8_621psYyPhbOwrNVSp3aYtkoRYlmMDajR2Awuh9vZYje-xjj1ZgYaFtnkuU2Nt84_KP2CqhHfmJ5RRI-dcmwr0UCtytL7S8tlyDJSnGK_6eW6XqCDC64jX_J49o0tSI_jxoTzD-RCqBwBcfg_m-aN5e530T_7wqOq-UcBQF5QP2iEtNS7CkdQR-OGtPuo238Nolvw4fSpHDCfHO950ddXu6Xo6Cj8q5xePfRdEH4-LtzCYmQW9N52qDDLNfbjNJYRuKB8B9KhGFD2Z6jaH33L7v-7WVELCscpz1dG3RmEciKK-30Ap93PaCfXQHBCt_RLStUYIh5OuS5MXw6lPeMyayWyorb2XzIbhTJ1GLrgVCY3-0m2icjx1GfxOv1u5nIsIiMjZ1GyP2lbab-WmwvG9i8kZ2BRbDUZBP_sOuAX4aa2lzUcQ5jscuGpJJMHJTzfCyNYv85nOi_xLvBLBgeJPuFh4NSeti2ItjCjxm3jykkeMFSX5NDa3W5ujIsed6ONjKxNWs5GFJAqIJCjbMn_lahXEz3ihuK1ztz0kT_uAY57n12Sw-kEttGJ5THvGo1c-9_tt-UYDPK7bRJm0ef9_qmXsMPrjV01gneke9gFCgkYNnnXwTr2w7XWPh7pas9SPYCtnC5LmV9MwIE08j9KuVnGl5qfVOga6
###

GET {{Restaurants.API_HostAddress}}/api/restaurants?searchPhrase=&pageSize=5&pageNumber=1&sortBy=Name&sortDirection=Descending
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/5
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "New test",
  "description": "new testing",
  "hasDelivery": false
}

### 

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Owner testing",
  "description": "Cool Place",
  "category": "Indian",
  "hasDelivery": true,
  "contactEmail": "info@test.com",
  "contactNumber": "555-1234",
  "city": "New York",
  "street": "1234 Main Street",
  "postalCode": "10-010"


}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/1/dishes

###

PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "Nationality": "French",
  "DateOfBirth": "2000-01-01"
}

###
